/* @flow */
export const CREATE_TODO_REQUEST: string = 'CREATE_TODO_REQUEST';
export const CREATE_TODO_SUCCESS: string = 'CREATE_TODO_SUCCESS';
export const CREATE_TODO_FAILURE: string = 'CREATE_TODO_FAILURE';

export const READ_TODOS_REQUEST: string = 'READ_TODOS_REQUEST';
export const READ_TODOS_SUCCESS: string = 'READ_TODOS_SUCCESS';
export const READ_TODOS_FAILURE: string = 'READ_TODOS_FAILURE';

export const UPDATE_TODO_REQUEST: string = 'UPDATE_TODO_REQUEST';
export const UPDATE_TODO_SUCCESS: string = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_FAILURE: string = 'UPDATE_TODO_FAILURE';

export const DELETE_TODO_REQUEST: string = 'DELETE_TODO_REQUEST';
export const DELETE_TODO_SUCCESS: string = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_FAILURE: string = 'DELETE_TODO_FAILURE';
